### ISSUE TITLE
Plugin is not show in Plugins after installing

### ISSUE THREAD

**Issue by kubax** [jawilson/deluge-piaportplugin#1]
Hi,

i could not get this plugin to show under plugins.

I checked, and it is pushed to the plugins folder, but it does not seem to be used.

is there something special to do to make this work with the latest deluge image from linuxserver?

**Comment by kubax** [comment]
fixed it myself... had to manually build it with python 3.6. the Release is for python 3.8, but the container only support python 3.6

**Comment by kubax** [comment]
closed

**Comment by codetheweb** [comment]
Sorry about that, should be fixed in v0.1.1.

**Comment by kubax** [comment]
Tested, works as expected :)

Thanks for the Work!!
