### ISSUE TITLE
Question: automatically mapping ports in gluetun

### ISSUE THREAD

**Issue by addiebarron** [jawilson/deluge-piaportplugin#2]
Hello, thanks so much for creating this and saving me such a headache! I have a question about configuring this plugin with gluetun. 

My understanding is that in order for incoming connections to connect to deluge via the port that PIA has forwarded, the port would need to be mapped from the host to the gluetun container (and implicitly to deluge from there). I can understand mapping a port manually via a `ports` statement in the gluetun service, but since the port changes every time PIA changes it, would I need to update the `ports` statement manually every 60 days? Or am I misunderstanding how the system works?

Thank you!

**Comment by DcR-NL** [comment]
This isn't really the place to ask, but I will try to answer your question… No, simply said, you don't need to map the port; it's a port to access the VPN on PIA's side.

It's PIA that maps the port for you and redirects it to your private VPN tunnel. Deluge is on the same network as Gluetun (your private VPN tunnel) and listens to the port. As long as the VPN is up, the port is accessible from the outside to your gluetun network, no further configuration needed.

**Comment by addiebarron** [comment]
Got it! Appreciate the help, despite the misplacement. Maybe someone else will find this useful.
